## QUIZ 1 - Data Science with Python week 1 

In [60]:
import numpy as np 
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)


['bat', 'bot']


In [68]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [4]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(L)

5


In [16]:
import numpy as np 
a = np.random.random((20,20))
b = np.random.random((20,20))


In [69]:
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20)))

8.216660037426713

In [18]:
print(a)

[[0.03315466 0.19870333 0.46452957 0.0600994  0.573972   0.86304673
  0.46254299 0.06765874 0.41339295 0.27600344 0.70723316 0.41808555
  0.14709391 0.36546909 0.6377183  0.73158335 0.8405008  0.99709218
  0.55888841 0.21118734]
 [0.34845005 0.1071817  0.93816612 0.12170335 0.32433386 0.95544809
  0.2383106  0.77452398 0.87443797 0.63419995 0.4851143  0.35533591
  0.40360429 0.21693338 0.03606072 0.52406399 0.57445738 0.52745937
  0.71625206 0.39531623]
 [0.53533395 0.1286429  0.73372255 0.41860589 0.90940704 0.90825232
  0.97703433 0.72359087 0.41571014 0.49160981 0.32720152 0.75780772
  0.36635284 0.61391629 0.47353278 0.87977357 0.78955144 0.96996284
  0.26432755 0.00664021]
 [0.58720313 0.10642069 0.71676638 0.46182186 0.25889818 0.42003421
  0.32257837 0.60594369 0.10365779 0.01190958 0.79861198 0.07096937
  0.47279138 0.92644451 0.01354482 0.25075236 0.13522278 0.19080673
  0.57312211 0.59246775]
 [0.09272566 0.47739598 0.08211623 0.88046451 0.63703298 0.71162042
  0.29947542 0.3

In [19]:
l2_dist(a, b)

8.216660037426713

In [20]:
l2_dist(np.reshape(a, (20 * 20)), np.reshape(b, (20 * 20, 1)))

164.82603108065624

In [21]:
l2_dist(a.T, b.T)

8.216660037426713

In [22]:
a1 = np.random.rand(4)
a2 = np.random.rand(4, 1)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)


In [36]:
print(a5)
#print(a3.shape == a4.shape)
print(a5.shape == a1.shape)
#a1.shape == a2.shape
#a4.ndim() == 1

[1. 2. 3. 4.]
True


In [37]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [40]:
import re 
s = 'ACBCAC'
print(re.findall('^[AC]', s))
print(re.findall('AC', s))
print(re.findall('[^A]C', s))
print(re.findall('^AC', s))


['A']
['AC', 'AC']
['BC']
['AC']


In [41]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)
print(L)
print(result)

5
['A', 'AA', 'AA', 'AA', 'A']


In [47]:
s = 'Office of Research Administration: (734) 647-6333 | 4325 North Quad' + 'Office of Budget and Financial Administration: (734) 647-8044 | 309 Maynard, Suite 205' + 'Health Informatics Program: (734) 763-2285 | 333 Maynard, Suite 500'
#result = re.findall('\d{3}[-]\d{3}[-]\d{4}', s)
#result = re.findall('\d{3}\s\d{3}[-]\d{4}', s)
#result = re.findall('[(]\d{3}[)]\d{3}[-]\d{4}', s)
result = re.findall('[(]\d{3}[)]\s\d{3}[-]\d{4}', s)
print(result)

['(734) 647-6333', '(734) 647-8044', '(734) 763-2285']


In [59]:
s = 'I refer to https://google.com and I never refer http://www.baidu.com if I have to search anything'
#result = re.findall('(?<=https:\/\/)([A-Za-z0-9]*)', s)
result = re.findall('(?<=[https]:\/\/)([A-Za-z0-9.]*)', s)
#result = re.findall('(?<=https:\/\/)([.]*)', s)
#result = re.findall('(?<=https:\/\/)([A-Za-z0-9.]*)', s)
print(result)

['google.com', 'www.baidu.com']


In [67]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4
